# Generated by Django 5.1.5 on 2025-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraLocation',
            fields=[
                ('cam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CAM_LOC',
                'managed': False,
            },
        ),
    ]
