# Generated by Django 5.1.5 on 2025-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_rating_count_userprofile_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
