# Generated by Django 5.1.5 on 2025-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
