# Generated by Django 5.1.5 on 2025-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
