# Generated by Django 5.1.5 on 2025-03-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_available_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='verified',
        ),
    ]
